# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Workspace/Chegg/TCPMultithreadedServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Workspace/Chegg/TCPMultithreadedServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Workspace/Chegg/TCPMultithreadedServer/CMakeFiles /mnt/c/Workspace/Chegg/TCPMultithreadedServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Workspace/Chegg/TCPMultithreadedServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tcp_client

# Build rule for target.
tcp_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_client
.PHONY : tcp_client

# fast build rule for target.
tcp_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/build
.PHONY : tcp_client/fast

#=============================================================================
# Target rules for targets named tcp_server

# Build rule for target.
tcp_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_server
.PHONY : tcp_server

# fast build rule for target.
tcp_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/build
.PHONY : tcp_server/fast

client_example.o: client_example.cpp.o

.PHONY : client_example.o

# target to build an object file
client_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/client_example.cpp.o
.PHONY : client_example.cpp.o

client_example.i: client_example.cpp.i

.PHONY : client_example.i

# target to preprocess a source file
client_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/client_example.cpp.i
.PHONY : client_example.cpp.i

client_example.s: client_example.cpp.s

.PHONY : client_example.s

# target to generate assembly for a file
client_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/client_example.cpp.s
.PHONY : client_example.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/main.cpp.s
.PHONY : main.cpp.s

src/RequestParser.o: src/RequestParser.cpp.o

.PHONY : src/RequestParser.o

# target to build an object file
src/RequestParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/RequestParser.cpp.o
.PHONY : src/RequestParser.cpp.o

src/RequestParser.i: src/RequestParser.cpp.i

.PHONY : src/RequestParser.i

# target to preprocess a source file
src/RequestParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/RequestParser.cpp.i
.PHONY : src/RequestParser.cpp.i

src/RequestParser.s: src/RequestParser.cpp.s

.PHONY : src/RequestParser.s

# target to generate assembly for a file
src/RequestParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/RequestParser.cpp.s
.PHONY : src/RequestParser.cpp.s

src/client.o: src/client.cpp.o

.PHONY : src/client.o

# target to build an object file
src/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/client.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/client.cpp.o
.PHONY : src/client.cpp.o

src/client.i: src/client.cpp.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/client.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/client.cpp.i
.PHONY : src/client.cpp.i

src/client.s: src/client.cpp.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/client.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/client.cpp.s
.PHONY : src/client.cpp.s

src/message_board.o: src/message_board.cpp.o

.PHONY : src/message_board.o

# target to build an object file
src/message_board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/message_board.cpp.o
.PHONY : src/message_board.cpp.o

src/message_board.i: src/message_board.cpp.i

.PHONY : src/message_board.i

# target to preprocess a source file
src/message_board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/message_board.cpp.i
.PHONY : src/message_board.cpp.i

src/message_board.s: src/message_board.cpp.s

.PHONY : src/message_board.s

# target to generate assembly for a file
src/message_board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/message_board.cpp.s
.PHONY : src/message_board.cpp.s

src/post.o: src/post.cpp.o

.PHONY : src/post.o

# target to build an object file
src/post.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/post.cpp.o
.PHONY : src/post.cpp.o

src/post.i: src/post.cpp.i

.PHONY : src/post.i

# target to preprocess a source file
src/post.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/post.cpp.i
.PHONY : src/post.cpp.i

src/post.s: src/post.cpp.s

.PHONY : src/post.s

# target to generate assembly for a file
src/post.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/post.cpp.s
.PHONY : src/post.cpp.s

src/tcp_client.o: src/tcp_client.cpp.o

.PHONY : src/tcp_client.o

# target to build an object file
src/tcp_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/tcp_client.cpp.o
.PHONY : src/tcp_client.cpp.o

src/tcp_client.i: src/tcp_client.cpp.i

.PHONY : src/tcp_client.i

# target to preprocess a source file
src/tcp_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/tcp_client.cpp.i
.PHONY : src/tcp_client.cpp.i

src/tcp_client.s: src/tcp_client.cpp.s

.PHONY : src/tcp_client.s

# target to generate assembly for a file
src/tcp_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/tcp_client.cpp.s
.PHONY : src/tcp_client.cpp.s

src/tcp_server.o: src/tcp_server.cpp.o

.PHONY : src/tcp_server.o

# target to build an object file
src/tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/tcp_server.cpp.o
.PHONY : src/tcp_server.cpp.o

src/tcp_server.i: src/tcp_server.cpp.i

.PHONY : src/tcp_server.i

# target to preprocess a source file
src/tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/tcp_server.cpp.i
.PHONY : src/tcp_server.cpp.i

src/tcp_server.s: src/tcp_server.cpp.s

.PHONY : src/tcp_server.s

# target to generate assembly for a file
src/tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/tcp_server.cpp.s
.PHONY : src/tcp_server.cpp.s

src/topic.o: src/topic.cpp.o

.PHONY : src/topic.o

# target to build an object file
src/topic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/topic.cpp.o
.PHONY : src/topic.cpp.o

src/topic.i: src/topic.cpp.i

.PHONY : src/topic.i

# target to preprocess a source file
src/topic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/topic.cpp.i
.PHONY : src/topic.cpp.i

src/topic.s: src/topic.cpp.s

.PHONY : src/topic.s

# target to generate assembly for a file
src/topic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/topic.cpp.s
.PHONY : src/topic.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tcp_client"
	@echo "... tcp_server"
	@echo "... client_example.o"
	@echo "... client_example.i"
	@echo "... client_example.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/RequestParser.o"
	@echo "... src/RequestParser.i"
	@echo "... src/RequestParser.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/message_board.o"
	@echo "... src/message_board.i"
	@echo "... src/message_board.s"
	@echo "... src/post.o"
	@echo "... src/post.i"
	@echo "... src/post.s"
	@echo "... src/tcp_client.o"
	@echo "... src/tcp_client.i"
	@echo "... src/tcp_client.s"
	@echo "... src/tcp_server.o"
	@echo "... src/tcp_server.i"
	@echo "... src/tcp_server.s"
	@echo "... src/topic.o"
	@echo "... src/topic.i"
	@echo "... src/topic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

